openapi: 3.0.0
info:
  title: Collector-Events API
  version: 1.0.0
  description: API documentation for Collector-Events microservice
  contact:
    name: Javier Fern√°ndez-Castillo
    email: jfernandez26@us.es
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
servers:
  - url: /api
paths:
  /computations:
    get:
      summary: Get all current computations
      tags:
        - Computation
      responses:
        '200':
          description: A list of computations
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Current computations fetched successfully. Total: 0'
                  data:
                    type: array
                    example: []
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2025-08-13T22:56:33.429Z'
    delete:
      summary: Delete all computations
      tags:
        - Computation
      responses:
        '200':
          description: All computations deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'All computations deleted successfully. Total deleted: 1'
                  data:
                    type: 'null'
                    example: null
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2025-08-13T22:55:02.648Z'
    post:
      summary: Create a new computation
      tags:
        - Computation
      parameters:
        - in: header
          name: token
          required: true
          description: Token for authentication with external APIs
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComputationForm'
      responses:
        '201':
          description: The created computation (in progress)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InProgressComputation'
  /computations/{id}:
    get:
      summary: Get a computation by ID
      tags:
        - Computation
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the computation to get
          schema:
            type: string
      responses:
        '200':
          description: The requested computation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CompletedComputation'
                  - $ref: '#/components/schemas/AbortedComputation'
        '202':
          description: Computation is still in progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InProgressComputation'
        '404':
          description: Computation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundComputation'
components:
  schemas:
    CreateComputationForm:
      type: object
      properties:
        api:
          type: object
          properties:
            name:
              type: string
              example: github
            endpoint:
              type: string
              example: https://api.github.com/repos/governify/bluejay-showcase/pulls?state=all
          required:
            - name
            - endpoint
      required:
        - api
      example:
        api:
          name: github
          endpoint: https://api.github.com/repos/governify/bluejay-showcase/pulls?state=all
    InProgressComputation:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: 'Computation with id: 8b33bba178a142c9 started successfully'
        data:
          type: object
          properties:
            id:
              type: string
              example: 8b33bba178a142c9
            state:
              type: string
              example: In Progress
        appCode:
          type: string
          example: OK
        timestamp:
          type: string
          example: '2025-08-13T22:13:06.546Z'
      example:
        status: success
        message: 'Computation with id: 8b33bba178a142c9 started successfully'
        data:
          id: 8b33bba178a142c9
          state: In Progress
        appCode: OK
        timestamp: '2025-08-13T22:13:06.546Z'
    CompletedComputation:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: 'Retrieving computation with id: 65cccae28b031340'
        data:
          type: object
          properties:
            id:
              type: string
              example: 65cccae28b031340
            state:
              type: string
              example: Completed
            totalCount:
              type: integer
              example: 1
            computationRequestConfig:
              type: object
              properties:
                api:
                  type: object
                  properties:
                    name:
                      type: string
                      example: github
                    endpoint:
                      type: string
                      example: https://api.github.com/repos/governify/bluejay-showcase/pulls?state=all
                  required:
                    - name
                    - endpoint
              required:
                - api
            computation:
              type: array
              items:
                type: object
                properties:
                  title:
                    type: string
                    example: Pull Request Title
        appCode:
          type: string
          example: OK
        timestamp:
          type: string
          example: '2025-08-13T22:14:45.912Z'
      example:
        status: success
        message: 'Retrieving computation with id: 65cccae28b031340'
        data:
          id: 65cccae28b031340
          state: Completed
          totalCount: 1
          computationRequestConfig:
            api:
              name: github
              endpoint: https://api.github.com/repos/governify/bluejay-showcase/pulls?state=all
          computation:
            - title: Pull Request Title
        appCode: OK
        timestamp: '2025-08-13T22:14:45.912Z'
    AbortedComputation:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: 'Computation with id: 5b664efd8371206d started successfully'
        data:
          type: object
          properties:
            id:
              type: string
              example: 5b664efd8371206d
            state:
              type: string
              example: Aborted
        appCode:
          type: string
          example: OK
        timestamp:
          type: string
          example: '2025-08-13T22:23:50.156Z'
      example:
        status: success
        message: 'Computation with id: 5b664efd8371206d started successfully'
        data:
          id: 5b664efd8371206d
          state: Aborted
        appCode: OK
        timestamp: '2025-08-13T22:23:50.156Z'
    NotFoundComputation:
      type: object
      properties:
        status:
          type: string
          example: failed
        message:
          type: string
          example: No computation with the id 3484ec9380ec4140 was found.
        details:
          type: object
        appCode:
          type: string
          example: NOT_FOUND
        statusCode:
          type: integer
          example: 404
        timestamp:
          type: string
          example: '2025-08-13T22:33:02.468Z'
      example:
        status: failed
        message: 'No computation with this id was found.'
        details: {}
        appCode: NOT_FOUND
        statusCode: 404
        timestamp: '2025-08-13T22:33:02.468Z'
